### ISSUE TITLE
Use include <cmath>

### ISSUE THREAD

**Issue by fire** [elasota/ConvectionKernels#5]
thirdparty/cvtt/ConvectionKernels_ETC.cpp:3134:55: error: no member named 'sqrt' in namespace 'std'
    const float lengthRatio = static_cast<float>(std::sqrt(ca0LengthSq / ca1UNLengthSq));
                                                 ~~~~~^

Please use `#include <cmath>`.

**Comment by elasota** [comment]
Fixed by dc2dbbe0ae2cf2be06ef56d1021e2222a56c7fe2
